import { useTranslation } from "react-i18next";

export const teachings = [
    {
        id: '1ssdd', 
        title: 'umrah_step',
        body: 'umrah_step_body'
    },
    {
        id: '2ssdefr', 
        title: 'Code is a two-dimensional version of the barcode, typically made up of black ',
        body: 'QR Code is a two-dimensional version of the barcode, typically made up of black and white pixel patterns. Denso Wave, a Japanese subsidiary of the Toyota supplier Denso, developed them for marking components in order to accelerate logistics processes for their automobile production. Now, it has found its way into mobile marketing with the widespread adoption of smartphones. "QR" stands for "Quick Response", which refers to the instant access to the information hidden in the Code.QR Code is a two-dimensional version of the barcode, typically made up of black and white pixel patterns. Denso Wave, a Japanese subsidiary of the Toyota supplier Denso, developed them for marking components in order to accelerate logistics processes for their automobile production. Now, it has found its way into mobile marketing with the widespread adoption of smartphones. "QR" stands for "Quick Response", which refers to the instant access to the information hidden in the Code.QR Code is a two-dimensional version of the barcode, typically made up of black and white pixel patterns. Denso Wave, a Japanese subsidiary of the Toyota supplier Denso, developed them for marking components in order to accelerate logistics processes for their automobile production. Now, it has found its way into mobile marketing with the widespread adoption of smartphones. "QR" stands for "Quick Response", which refers to the instant access to the information hidden in the Code.'
    },
    {
        id: '3wssedrr', 
        title: 'barcode, typically made up of black and white pixel patterns. De',
        body: 'QR Code is a two-dimensional version of the barcode, typically made up of black and white pixel patterns. Denso Wave, a Japanese subsidiary of the Toyota supplier Denso, developed them for marking components in order to accelerate logistics processes for their automobile production. Now, it has found its way into mobile marketing with the widespread adoption of smartphones. "QR" stands for "Quick Response", which refers to the instant access to the information hidden in the Code.QR Code is a two-dimensional version of the barcode, typically made up of black and white pixel patterns. Denso Wave, a Japanese subsidiary of the Toyota supplier Denso, developed them for marking components in order to accelerate logistics processes for their automobile production. Now, it has found its way into mobile marketing with the widespread adoption of smartphones. "QR" stands for "Quick Response", which refers to the instant access to the information hidden in the Code.QR Code is a two-dimensional version of the barcode, typically made up of black and white pixel patterns. Denso Wave, a Japanese subsidiary of the Toyota supplier Denso, developed them for marking components in order to accelerate logistics processes for their automobile production. Now, it has found its way into mobile marketing with the widespread adoption of smartphones. "QR" stands for "Quick Response", which refers to the instant access to the information hidden in the Code.'
    },
    {
        id: '4sdwsxc', 
        title: 'Namna bora ya kufanya Umrah hatua kwa hatua',
        body: 'QR Code is a two-dimensional version of the barcode, typically made up of black and white pixel patterns. Denso Wave, a Japanese subsidiary of the Toyota supplier Denso, developed them for marking components in order to accelerate logistics processes for their automobile production. Now, it has found its way into mobile marketing with the widespread adoption of smartphones. "QR" stands for "Quick Response", which refers to the instant access to the information hidden in the Code.QR Code is a two-dimensional version of the barcode, typically made up of black and white pixel patterns. Denso Wave, a Japanese subsidiary of the Toyota supplier Denso, developed them for marking components in order to accelerate logistics processes for their automobile production. Now, it has found its way into mobile marketing with the widespread adoption of smartphones. "QR" stands for "Quick Response", which refers to the instant access to the information hidden in the Code.QR Code is a two-dimensional version of the barcode, typically made up of black and white pixel patterns. Denso Wave, a Japanese subsidiary of the Toyota supplier Denso, developed them for marking components in order to accelerate logistics processes for their automobile production. Now, it has found its way into mobile marketing with the widespread adoption of smartphones. "QR" stands for "Quick Response", which refers to the instant access to the information hidden in the Code.'
    },
    {
        id: '5ssqazxcf', 
        title: 'Namna bora ya kufanya Umrah hatua kwa hatua',
        body: 'QR Code is a two-dimensional version of the barcode, typically made up of black and white pixel patterns. Denso Wave, a Japanese subsidiary of the Toyota supplier Denso, developed them for marking components in order to accelerate logistics processes for their automobile production. Now, it has found its way into mobile marketing with the widespread adoption of smartphones. "QR" stands for "Quick Response", which refers to the instant access to the information hidden in the Code.QR Code is a two-dimensional version of the barcode, typically made up of black and white pixel patterns. Denso Wave, a Japanese subsidiary of the Toyota supplier Denso, developed them for marking components in order to accelerate logistics processes for their automobile production. Now, it has found its way into mobile marketing with the widespread adoption of smartphones. "QR" stands for "Quick Response", which refers to the instant access to the information hidden in the Code.QR Code is a two-dimensional version of the barcode, typically made up of black and white pixel patterns. Denso Wave, a Japanese subsidiary of the Toyota supplier Denso, developed them for marking components in order to accelerate logistics processes for their automobile production. Now, it has found its way into mobile marketing with the widespread adoption of smartphones. "QR" stands for "Quick Response", which refers to the instant access to the information hidden in the Code.'
    },
    {
        id: '6sedx3edd', 
        title: 'ck and white pixel patterns. Denso Wave, a Ja',
        body: 'QR Code is a two-dimensional version of the barcode, typically made up of black and white pixel patterns. Denso Wave, a Japanese subsidiary of the Toyota supplier Denso, developed them for marking components in order to accelerate logistics processes for their automobile production. Now, it has found its way into mobile marketing with the widespread adoption of smartphones. "QR" stands for "Quick Response", which refers to the instant access to the information hidden in the Code.QR Code is a two-dimensional version of the barcode, typically made up of black and white pixel patterns. Denso Wave, a Japanese subsidiary of the Toyota supplier Denso, developed them for marking components in order to accelerate logistics processes for their automobile production. Now, it has found its way into mobile marketing with the widespread adoption of smartphones. "QR" stands for "Quick Response", which refers to the instant access to the information hidden in the Code.QR Code is a two-dimensional version of the barcode, typically made up of black and white pixel patterns. Denso Wave, a Japanese subsidiary of the Toyota supplier Denso, developed them for marking components in order to accelerate logistics processes for their automobile production. Now, it has found its way into mobile marketing with the widespread adoption of smartphones. "QR" stands for "Quick Response", which refers to the instant access to the information hidden in the Code.'
    },
]

export const news = [
    {
        id: '1hhjjik1',
        title: 'hijja_2023_lottery_title',
        url:'https://images.unsplash.com/photo-1417325384643-aac51acc9e5d?q=75&fm=jpg',
        body: 'hijja_2023_lottery_body'  
    },
    {
        id: '274uuhg4',
        title: 'Waaislamu kutoka Tanzania sasa, kuomba hija kwa mtandao',
        url:'https://images.unsplash.com/5/unsplash-kitsune-4.jpg?ixlib=rb-0.3.5&q=85&fm=jpg&crop=entropy&cs=srgb&ixid=eyJhcHBfaWQiOjEyMDd9&s=ce40ce8b8ba365e5e6d06401e5485390',
        body: 'QR Code is a two-dimensional version of the barcode, typically made up of black and white pixel patterns. Denso Wave, a Japanese subsidiary of the Toyota supplier Denso, developed them for marking components in order to accelerate logistics processes for their automobile production. Now, it has found its way into mobile marketing with the widespread adoption of smartphones. "QR" stands for "Quick Response", which refers to the instant access to the information hidden in the Code.QR Code is a two-dimensional version of the barcode, typically made up of black and white pixel patterns. Denso Wave, a Japanese subsidiary of the Toyota supplier Denso, developed them for marking components in order to accelerate logistics processes for their automobile production. Now, it has found its way into mobile marketing with the widespread adoption of smartphones. "QR" stands for "Quick Response", which refers to the instant access to the information hidden in the Code.QR Code is a two-dimensional version of the barcode, typically made up of black and white pixel patterns. Denso Wave, a Japanese subsidiary of the Toyota supplier Denso, developed them for marking components in order to accelerate logistics processes for their automobile production. Now, it has found its way into mobile marketing with the widespread adoption of smartphones. "QR" stands for "Quick Response", which refers to the instant access to the information hidden in the Code.'  
    },
    {
        id: '3334rrft',
        title: 'Utaraibu mpya wa hija na umrah 2023',
        url:'https://images.unsplash.com/1/type-away.jpg?q=80&fm=jpg',
        body: 'QR Code is a two-dimensional version of the barcode, typically made up of black and white pixel patterns. Denso Wave, a Japanese subsidiary of the Toyota supplier Denso, developed them for marking components in order to accelerate logistics processes for their automobile production. Now, it has found its way into mobile marketing with the widespread adoption of smartphones. "QR" stands for "Quick Response", which refers to the instant access to the information hidden in the Code.QR Code is a two-dimensional version of the barcode, typically made up of black and white pixel patterns. Denso Wave, a Japanese subsidiary of the Toyota supplier Denso, developed them for marking components in order to accelerate logistics processes for their automobile production. Now, it has found its way into mobile marketing with the widespread adoption of smartphones. "QR" stands for "Quick Response", which refers to the instant access to the information hidden in the Code.QR Code is a two-dimensional version of the barcode, typically made up of black and white pixel patterns. Denso Wave, a Japanese subsidiary of the Toyota supplier Denso, developed them for marking components in order to accelerate logistics processes for their automobile production. Now, it has found its way into mobile marketing with the widespread adoption of smartphones. "QR" stands for "Quick Response", which refers to the instant access to the information hidden in the Code.'  
    },
    {
        id: '4sswedd45g',
        title: 'Utaraibu mpya wa hija na umrah 2023',
        url:'https://images.unsplash.com/1/type-away.jpg?q=80&fm=jpg',
        body: 'QR Code is a two-dimensional version of the barcode, typically made up of black and white pixel patterns. Denso Wave, a Japanese subsidiary of the Toyota supplier Denso, developed them for marking components in order to accelerate logistics processes for their automobile production. Now, it has found its way into mobile marketing with the widespread adoption of smartphones. "QR" stands for "Quick Response", which refers to the instant access to the information hidden in the Code.QR Code is a two-dimensional version of the barcode, typically made up of black and white pixel patterns. Denso Wave, a Japanese subsidiary of the Toyota supplier Denso, developed them for marking components in order to accelerate logistics processes for their automobile production. Now, it has found its way into mobile marketing with the widespread adoption of smartphones. "QR" stands for "Quick Response", which refers to the instant access to the information hidden in the Code.QR Code is a two-dimensional version of the barcode, typically made up of black and white pixel patterns. Denso Wave, a Japanese subsidiary of the Toyota supplier Denso, developed them for marking components in order to accelerate logistics processes for their automobile production. Now, it has found its way into mobile marketing with the widespread adoption of smartphones. "QR" stands for "Quick Response", which refers to the instant access to the information hidden in the Code.'  
    }
]

export const questions = [
    {id: '555d5d5d5', title: 'period_hajj', body:'QR Code is a two-dimensional version of the barcode, typically made up of black and white pixel patterns. Denso Wave, a Japanese subsidiary of the Toyota supplier Denso, developed them for marking components in order to accelerate logistics processes for their automobile production. Now, it has found its way into mobile marketing with the widespread adoption of smartphones. "QR" stands for "Quick Response", which refers to the instant access to the information hidden in the Code.QR Code is a two-dimensional version of the barcode, typically made up of black and white pixel patterns. Denso Wave, a Japanese subsidiary of the Toyota supplier Denso, developed them for marking components in order to accelerate logistics processes for their automobile production. Now, it has found its way into mobile marketing with the widespread adoption of smartphones. "QR" stands for "Quick Response", which refers to the instant access to the information hidden in the Code.QR Code is a two-dimensional version of the barcode, typically made up of black and white pixel patterns. Denso Wave, a Japanese subsidiary of the Toyota supplier Denso, developed them for marking components in order to accelerate logistics processes for their automobile production. Now, it has found its way into mobile marketing with the widespread adoption of smartphones. "QR" stands for "Quick Response", which refers to the instant access to the information hidden in the Code'},
    {id: '555dddd5d5d5', title: 'women_harem', body:'QR Code is a two-dimensional version of the barcode, typically made up of black and white pixel patterns. Denso Wave, a Japanese subsidiary of the Toyota supplier Denso, developed them for marking components in order to accelerate logistics processes for their automobile production. Now, it has found its way into mobile marketing with the widespread adoption of smartphones. "QR" stands for "Quick Response", which refers to the instant access to the information hidden in the Code.QR Code is a two-dimensional version of the barcode, typically made up of black and white pixel patterns. Denso Wave, a Japanese subsidiary of the Toyota supplier Denso, developed them for marking components in order to accelerate logistics processes for their automobile production. Now, it has found its way into mobile marketing with the widespread adoption of smartphones. "QR" stands for "Quick Response", which refers to the instant access to the information hidden in the Code.QR Code is a two-dimensional version of the barcode, typically made up of black and white pixel patterns. Denso Wave, a Japanese subsidiary of the Toyota supplier Denso, developed them for marking components in order to accelerate logistics processes for their automobile production. Now, it has found its way into mobile marketing with the widespread adoption of smartphones. "QR" stands for "Quick Response", which refers to the instant access to the information hidden in the Code'},
    {id: '555wwwd5d5d5', title: 'Unaweza ukahiji kila mwaka?', body:'QR Code is a two-dimensional version of the barcode, typically made up of black and white pixel patterns. Denso Wave, a Japanese subsidiary of the Toyota supplier Denso, developed them for marking components in order to accelerate logistics processes for their automobile production. Now, it has found its way into mobile marketing with the widespread adoption of smartphones. "QR" stands for "Quick Response", which refers to the instant access to the information hidden in the Code.QR Code is a two-dimensional version of the barcode, typically made up of black and white pixel patterns. Denso Wave, a Japanese subsidiary of the Toyota supplier Denso, developed them for marking components in order to accelerate logistics processes for their automobile production. Now, it has found its way into mobile marketing with the widespread adoption of smartphones. "QR" stands for "Quick Response", which refers to the instant access to the information hidden in the Code.QR Code is a two-dimensional version of the barcode, typically made up of black and white pixel patterns. Denso Wave, a Japanese subsidiary of the Toyota supplier Denso, developed them for marking components in order to accelerate logistics processes for their automobile production. Now, it has found its way into mobile marketing with the widespread adoption of smartphones. "QR" stands for "Quick Response", which refers to the instant access to the information hidden in the Code'},
    {id: '555drrr5d5d5', title: 'Ikitokea umepata hedhi katikati ya hija, unafanyaje?', body:'QR Code is a two-dimensional version of the barcode, typically made up of black and white pixel patterns. Denso Wave, a Japanese subsidiary of the Toyota supplier Denso, developed them for marking components in order to accelerate logistics processes for their automobile production. Now, it has found its way into mobile marketing with the widespread adoption of smartphones. "QR" stands for "Quick Response", which refers to the instant access to the information hidden in the Code.QR Code is a two-dimensional version of the barcode, typically made up of black and white pixel patterns. Denso Wave, a Japanese subsidiary of the Toyota supplier Denso, developed them for marking components in order to accelerate logistics processes for their automobile production. Now, it has found its way into mobile marketing with the widespread adoption of smartphones. "QR" stands for "Quick Response", which refers to the instant access to the information hidden in the Code.QR Code is a two-dimensional version of the barcode, typically made up of black and white pixel patterns. Denso Wave, a Japanese subsidiary of the Toyota supplier Denso, developed them for marking components in order to accelerate logistics processes for their automobile production. Now, it has found its way into mobile marketing with the widespread adoption of smartphones. "QR" stands for "Quick Response", which refers to the instant access to the information hidden in the Code'},

]

export const services = ['Hoteli nyota 5','Hoteli nyota 4','Tiketi za ndege', 'Mahema ukiwa Minna', 'Visa', 'Kuchinja', 'Usafiri wa Ndani Makka na Madina', 'Chai, Kahawa na Vitafunwa muda wote', 'Msaidizi', ' Vazi la Ihramu 1', 'Kitabu cha Muongozo wa Hijja', 'Simu na Laini yake', 'Chanjo zote', 'Kadi ya Kifalme' ]


export const regions = [
    {id: '1241', name: 'Arusha', districts: ["Arusha","Karatu","Longido","Meru","Monduli","Ngorongoro"]},
    {id: '124d1', name: 'Dar es Salaam', districts: ["Ilala","Kinondoni","Temeke","Kigamboni","Ubungo"]},
    {id: '12444d1', name: 'Dodoma', districts: ["Dodoma","Bahi","Chamwino","Chemba","Kondoa","Kongwa","Mpwapwa"]},
    {id: '44d1', name: 'Geita', districts: ["Geita Urban","Bukombe","Chato","Geita","Mbogwe","Nyang'hwale"]},
    {id: '44dff1', name: 'Iringa', districts: ["Iringa Rural","Iringa Urban","Kilolo","Mafinga","Mufindi"]},
    {id: '44dfsf1', name: 'Kagera', districts: ["Biharamulo","Bukoba Rural","Bukoba Urban","Karagwe","Kyerwa","Missenyi","Muleba","Ngara"]},
    {id: 'fsf1', name: 'Katavi', districts: ["Mlele","Mpanda"]},
    {id: 'fsddf1', name: 'Kigoma', districts: ["Buhigwe","Kakonko","Kasulu Rural","Kasulu Urban","Kibondo","Kigoma","Kigoma-Ujiji","Uvinza"]},
    {id: 'fsdfdf1', name: 'Kilimanjaro', districts: ["Hai","Moshi","Moshi Rural","Mwanga","Rombo","Same","Siha"]},
    {id: 'fsdufdf1', name: 'Lindi', districts: ["Kilwa","Lindi","Lindi Municipal","Liwale","Nachingwea","Ruangwa"]},
    {id: 'f78dufdf1', name: 'Manyara', districts: ["Babati","Hanang",,"Kiteto","Mbulu","Simanjiro"]},
    {id: 'f7fdf1', name: 'Mara', districts: ["Bunda","Butiama","Musoma Rural","Musoma Urban","Rorya","Serengeti","Tarime"]},
    {id: 'f7fdddf1', name: 'Mbeya', districts: ["Busokelo","Chunya","Kyela","Mbarali","Mbeya","Mbeya Rural","Rungwe"]},
    {id: 'f7fddyydf1', name: 'Morogoro', districts: ["Gairo","Kilombero","Kilosa","Malinyi","Morogoro Rural","Morogoro Urban","Mvomero","Ulanga"]},
    {id: 'f7f7ydf1', name: 'Mtwara', districts: ["Masasi","Masasi","Mtwara","Mikindani","Mtwara Rural","Mtwara-Mikindani","Nanyamba","Nanyumbu","Newala","Tandahimba"]},   
    {id: 'f7df89ydf1', name: 'Mwanza', districts: ["Ilemela","Kwimba","Magu","Misungwi","Nyamagana","Sengerema","Ukerewe"]},
    {id: 'f7889ydf1', name: 'Njombe', districts: ["Njombe","Ludewa","Makambako Urban","Makete","Njombe Rural","Njombe Urban","Wanging'ombe"]},
    {id: 'f7889ydf145', name: 'Pemba North', districts: ["Micheweni","Wete"]},
    {id: 'f7889yurr145', name: 'Pemba South', districts: ["Chake Chake","Mkoani"]},
    {id: 'f7889yu145', name: 'Pwani', districts: ["Bagamoyo"," Chalinze","Kibaha","Kibaha Urban","Kibiti","Kisarawe","Mafia","Mkuranga","Rufiji"]},
    {id: 'f788dd9yu145', name: 'Rukwa', districts: ["Kalambo","Lyamba lya Mfipa","Nkasi","Sumbawanga"]},
    {id: 'f89yu145', name: 'Ruvuma', districts: ["Mbinga","Namtumbo","Songea (rural)","Songea (urban)","Tunduru","Nyasa"]},
    {id: 'f89yffu145', name: 'Shinyanga', districts: ["Bariadi","Bukombe","Kahama","Maswa","Meatu","Shinyanga","Kishapu"]},
    {id: 'f89yffu1g45', name: 'Simiyu', districts: ["Bariadi","Busega","Itilima","Maswa","Meatu"]},
    {id: 'f89yffffu1g45', name: 'Singida', districts: ["Singida Rural","Singida Urban","Manyoni","Ikungi","Iramba","Mkalama"]},
    {id: '8yffffu1g45', name: 'Tabora', districts: ["Igunga","Kaliua","Nzega","Sikonge","Tabora Urban","Urambo","Uyui"]},
    {id: '8yfffggfu1g45', name: 'Tanga', districts: ["Tanga","Muheza","Korogwe","Lushoto","Handeni","Pangani","kilindi","Mkinga"]},
    {id: '8yu1g45', name: 'Zanzibar North', districts: ["Kaskazini A","Kaskazini B"]},
    {id: '8yu1ggqg45', name: 'Zanzibar South and central', districts: ["Kati","Kusini"]},
    {id: '8yu1gwwgqg45', name: 'Zanzibar West', districts: ["Magharibi","Mjini"]},

]